### ISSUE TITLE
{:error, :no_request} as result

### ISSUE THREAD

**Issue by krasnovandy** [tank-bohr/bookish_spork#47]
## What I've done

```
setup_all do
    {:ok, []} = HTTPoison.start()
    {:ok, _} = :bookish_spork.start_server()

{:ok, %{}}
end

test "just test" do
	:bookish_spork.stub_request([200, %{}, ""])


	api_endpoint = "http://localhost:32002/api"
	payload = "{\"destinations\":[],\"whatsApp\":{\"text\":\"Do Androids Dream of Electric Sheep?\"}}"
	get_headers = [
	  {"Authorization", "Basic Q1wewewewewewewewewewg=="},
	  {"accept", "application/json"},
	  {"Content-Type", "application/json"}
	]

	http_options = []

	result = HTTPoison.post(api_endpoint(), payload, get_headers(), http_options())

	{:ok, request} = :bookish_spork.capture_request()
end
```

## Actual result

```
** (MatchError) no match of right hand side value: {:error, :no_request}
     code: {:ok, request} = :bookish_spork.capture_request()
```

## Expected result

No error

## Environment
Erlang/OTP 20 
elixir  (1.8.1)
`  "bookish_spork": {:hex, :bookish_spork, "0.3.3", "975c93911dfef1e581b477348739ab388eff0e2edf329bc7668e7ecd10568af8", [:rebar3], [], "hexpm"},
`

**Comment by tank-bohr** [comment]
Hi @krasnovandy. Unfortunately I cannot reproduce your bug. I get a compilation errors when try to run your example

```
warning: variable "api_endpoint" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/bug47_test.exs:15: Bug47Test."test just test"/1

warning: variable "get_headers" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/bug47_test.exs:17: Bug47Test."test just test"/1

warning: variable "http_options" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/bug47_test.exs:23: Bug47Test."test just test"/1

warning: variable "request" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/bug47_test.exs:27: Bug47Test."test just test"/1

warning: variable "result" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/bug47_test.exs:25: Bug47Test."test just test"/1


== Compilation error in file test/bug47_test.exs ==
** (CompileError) test/bug47_test.exs:25: undefined function api_endpoint/0
    (elixir) src/elixir_locals.erl:98: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:98: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:237: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

After fixing compilation errors, test became green

**Comment by krasnovandy** [comment]
Hi @tank-bohr this is the right code
```
setup_all do
    {:ok, []} = HTTPoison.start()
    {:ok, _} = :bookish_spork.start_server()

{:ok, %{}}
end

test "just test" do
	:bookish_spork.stub_request([200, %{}, ""])


	api_endpoint = "http://localhost:32002/api"
	payload = "{\"destinations\":[],\"whatsApp\":{\"text\":\"Do Androids Dream of Electric Sheep?\"}}"
	get_headers = [
	  {"Authorization", "Basic Q1wewewewewewewewewewg=="},
	  {"accept", "application/json"},
	  {"Content-Type", "application/json"}
	]

	http_options = []

	result = HTTPoison.post(api_endpoint, payload, get_headers, http_options)

	{:ok, request} = :bookish_spork.capture_request()
end
```
 this test returns an error sometimes

**Comment by tank-bohr** [comment]
@krasnovandy I've run this code in a loop

```bash
for i in {1..100}; do mix test; done
```

and everything is ok. If you could reproduce the error in a stable way, then we will reopen this pull request
